Added better Groupassigner
Wruczek/ts-website pull request #83
Opened 2018-04-06 23:16 UTC by toster234

I am sending my **better version Group Assigner**.
Assigner has a login through the code that gets in a poke. 
**It is not possible** to change groups of another person.
Assigner is look nice.

### Configuration

1. Go to /config/assignerconfig.php
2. In line 5 you can change name of rank group
3. In line 6 you can change limit ranks from group
4. In line 7 you add id group

2018-04-07 17:38 UTC, derrobin154 commented
Your version is better than mine, but I programmed my groupassigner within 5 minutes :-D

2018-04-07 20:06 UTC, toster234 commented
Miss click....

2018-04-07 21:29 UTC, Wruczek approved these changes
Would be great to move CSS and JS to separate files

2018-04-07 21:31 UTC, derrobin154 commented
Can i make a German Language File in this Commit, or i must create a own commit?

2018-04-07 21:32 UTC, Wruczek commented
Not sure if this is possible, but try pushing to toster's repository to be included in this commit

2018-04-07 21:32 UTC, toster234 commented
> Can i make a German Language File in this Commit, or i must create a own commit?

Make PR in my repository

2018-04-07 21:36 UTC, derrobin154 requested changes
The Language URL is not found, the Language Code is not en_EN, the Code is en_US or en_GB

2018-04-07 21:39 UTC, derrobin154 approved these changes

2018-04-07 21:43 UTC, derrobin154 requested changes
Sorry, en_GB don't exist in this File.. you must take en_US

2018-04-07 21:45 UTC, toster234 commented
> Sorry, en_GB don't exist in this File.. you must take en_US

My bad i didn't test it.

2018-04-07 21:50 UTC, derrobin154 approved these changes

2018-04-07 22:04 UTC, Wruczek commented on assigner.php
> +    echo "<!-- IP: {$_SERVER["REMOTE_ADDR"]}, CFIP: {$_SERVER["HTTP_CF_CONNECTING_IP"]} -->";
The switch for real IP / proxy IP needs to not be hardcoded, rather added to the assigner config

2018-04-22 10:08 UTC, jakub96124124 commented
Uncaught TypeError: $(...).selectpicker is not a function
    at assigner.php:277


Please help thanks

2018-04-22 11:14 UTC, toster234 commented
> Uncaught TypeError: $(...).selectpicker is not a function
>at assigner.php:277
>
>Please help thanks

You didn't replace all files. You can download my fork of ts-website [https://github.com/toster234/ts-website](url)

2018-04-22 14:14 UTC, jakub96124124 commented
![image](https://user-images.githubusercontent.com/8945972/39095888-355ae256-4648-11e8-8d38-78a234761e29.png)

2018-04-22 17:17 UTC, toster234 commented
You can copy and paste link XD

2018-04-22 19:00 UTC, jakub96124124 commented
![image](https://user-images.githubusercontent.com/8945972/39098789-3f405b98-4670-11e8-9571-dd8a7737234a.png)

2018-04-24 18:22 UTC, jakub96124124 commented
Uncaught TypeError: $(...).selectpicker is not a function
at assigner.php:277

![](https://user-images.githubusercontent.com/8945972/39098789-3f405b98-4670-11e8-9571-dd8a7737234a.png)

2018-05-01 13:53 UTC, jakub96124124 commented
Uncaught TypeError: $(...).selectpicker is not a function
at assigner.php:277

No work

2018-12-28 10:04 UTC, Wruczek commented
2.0 ships with a group assigner, closing.

2018-12-28 10:04 UTC, closed without merging